name: CI

# Set default shell as interactive (source ~/.bashrc)
defaults:
  run:
    shell: bash -ieo pipefail {0}

# Run only one instance of this workflow at a time
# cancel-in-progress: stop running workflow and run latest instead
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  # Allow manual workflow runs
  workflow_dispatch:

jobs:

  lib:
    runs-on: self-hosted
    timeout-minutes: 5
    if: ${{ !cancelled() }}
    needs: []

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: run py2hwsw on lib
        run: |
          py2hwsw () { `pwd`/py2hwsw/scripts/py2hwsw.py $@; };\
          export -f py2hwsw;\
          for f in `find py2hwsw/lib -type f -name "*.py" ! -path "*/scripts/*" ! -name "csrs.py"`; do\
            py2hwsw `basename $f .py` print_build_dir;\
          done;


  iob-soc-lib:
    runs-on: self-hosted
    timeout-minutes: 10
    if: ${{ !cancelled() }}
    needs: [ lib ]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Clone iob-soc repo
        uses: actions/checkout@v4
        with:
          repository: IObundle/iob-soc
          path: iob-soc
          ref: if_gen2
          submodules: 'recursive'
      - name: run LIB test
        run: |
          export py2hwsw_dir=$(pwd);\
          py2hwsw () { $py2hwsw_dir/py2hwsw/scripts/py2hwsw.py $@; };\
          export -f py2hwsw;\
          cd iob-soc;\
          py2hwsw --version;\
          make -C lib/ sim-test;
